[package]
name = "neilos"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = { version = "0.28.1", features = ["event-stream"] }
expand = "0.3.0"
eyre = "0.6.12"
ratatui = "0.28.1"
tokio = { version = "1.40.0", features = ["full"] }
tokio-stream = "0.1.16"
